backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

media_library:
  name: default

collections:
  - name: "dummy"
    label: "Dummy"
    files:
      - name: "placeholder"
        label: "Placeholder"
        file: "data/placeholder.json"
        fields:
          - { label: "Title", name: "title", widget: "string" }
